apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-predictor
  namespace: ml-predictor
  labels:
    release: kube-prometheus-stack
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: ml-predictor
  namespaceSelector:
    matchNames:
      - ml-predictor
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
